<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  
  
  <title>TraceBack模块和Exception类 | DHao&#39;s Notebook</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="在python中，try…except用于捕获和处理异常，异常可能是由程序错误造成的，也可以通过raise语句手动抛出异常。traceback模块是一个格式化和打印异常及回溯的内建模块，一般不需要直接使用这个模块，本篇文章旨在探索traceback模块的一些细节。 sys 模块中的 exc_info 函数当程序抛出异常时，可以通过try…except语句进行捕获，也可以通过调用sys.exc_in">
<meta property="og:type" content="article">
<meta property="og:title" content="TraceBack模块和Exception类">
<meta property="og:url" content="http://example.com/2021/06/15/traceback/index.html">
<meta property="og:site_name" content="DHao&#39;s Notebook">
<meta property="og:description" content="在python中，try…except用于捕获和处理异常，异常可能是由程序错误造成的，也可以通过raise语句手动抛出异常。traceback模块是一个格式化和打印异常及回溯的内建模块，一般不需要直接使用这个模块，本篇文章旨在探索traceback模块的一些细节。 sys 模块中的 exc_info 函数当程序抛出异常时，可以通过try…except语句进行捕获，也可以通过调用sys.exc_in">
<meta property="og:locale" content="zh_CN">
<meta property="article:published_time" content="2021-06-15T08:00:00.000Z">
<meta property="article:modified_time" content="2021-07-08T08:26:02.075Z">
<meta property="article:author" content="DHao">
<meta property="article:tag" content="python">
<meta name="twitter:card" content="summary">
  
    <link rel="alternate" href="/atom.xml" title="DHao's Notebook" type="application/atom+xml">
  
  
    <link rel="shortcut icon" href="/favicon.png">
  
  
    
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/typeface-source-code-pro@0.0.71/index.min.css">

  
  
<link rel="stylesheet" href="/css/style.css">

  
    
<link rel="stylesheet" href="/fancybox/jquery.fancybox.min.css">

  
<meta name="generator" content="Hexo 5.4.0"></head>

<body>
  <div id="container">
    <div id="wrap">
      <header id="header">
  <div id="banner"></div>
  <div id="header-outer" class="outer">
    <div id="header-title" class="inner">
      <h1 id="logo-wrap">
        <a href="/" id="logo">DHao&#39;s Notebook</a>
      </h1>
      
    </div>
    <div id="header-inner" class="inner">
      <nav id="main-nav">
        <a id="main-nav-toggle" class="nav-icon"></a>
        
          <a class="main-nav-link" href="/">Home</a>
        
          <a class="main-nav-link" href="/archives">Archives</a>
        
      </nav>
      <nav id="sub-nav">
        
          <a id="nav-rss-link" class="nav-icon" href="/atom.xml" title="Flux RSS"></a>
        
        <a id="nav-search-btn" class="nav-icon" title="Rechercher"></a>
      </nav>
      <div id="search-form-wrap">
        <form action="//google.com/search" method="get" accept-charset="UTF-8" class="search-form"><input type="search" name="q" class="search-form-input" placeholder="Rechercher"><button type="submit" class="search-form-submit">&#xF002;</button><input type="hidden" name="sitesearch" value="http://example.com"></form>
      </div>
    </div>
  </div>
</header>

      <div class="outer">
        <section id="main"><article id="post-traceback" class="h-entry article article-type-post" itemprop="blogPost" itemscope itemtype="https://schema.org/BlogPosting">
  <div class="article-meta">
    <a href="/2021/06/15/traceback/" class="article-date">
  <time class="dt-published" datetime="2021-06-15T08:00:00.000Z" itemprop="datePublished">2021-06-15</time>
</a>
    
  </div>
  <div class="article-inner">
    
    
      <header class="article-header">
        
  
    <h1 class="p-name article-title" itemprop="headline name">
      TraceBack模块和Exception类
    </h1>
  

      </header>
    
    <div class="e-content article-entry" itemprop="articleBody">
      
        <p>在python中，try…except用于捕获和处理异常，异常可能是由程序错误造成的，也可以通过raise语句手动抛出异常。traceback模块是一个格式化和打印异常及回溯的内建模块，一般不需要直接使用这个模块，本篇文章旨在探索traceback模块的一些细节。</p>
<h2 id="sys-模块中的-exc-info-函数"><a href="#sys-模块中的-exc-info-函数" class="headerlink" title="sys 模块中的 exc_info 函数"></a>sys 模块中的 exc_info 函数</h2><p>当程序抛出异常时，可以通过try…except语句进行捕获，也可以通过调用sys.exc_info()函数来获取异常信息。sys.exc_info()返回一个三元数组，包括异常类，异常实例和traceback实例。</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">raise</span> TypeError(<span class="string">&quot;msg&quot;</span>)</span><br><span class="line"><span class="keyword">except</span> <span class="keyword">as</span> e:</span><br><span class="line">    exc = sys.exc_info()</span><br><span class="line">    <span class="comment"># exc = (TypeError，TypeError(&quot;msg&quot;)，&lt;traceback object at ...&gt;)</span></span><br><span class="line">    <span class="comment"># e = TypeError(&quot;msg&quot;)</span></span><br></pre></td></tr></table></figure>

<p>当通过raise语句抛出异常之后，或者在在except代码块中执行时，sys.exc_info()返回当前的异常，当处理完异常之后，sys.exc_info()返回None。在try…except as e结构中捕获异常之后，异常对象的属性中已经包含了这个三元数组的所有信息.</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">...</span><br><span class="line"><span class="keyword">assert</span> exc[<span class="number">0</span>] == e.__class__</span><br><span class="line"><span class="keyword">assert</span> exc[<span class="number">1</span>] == e</span><br><span class="line"><span class="keyword">assert</span> exc[<span class="number">2</span>] == e.__traceback__</span><br></pre></td></tr></table></figure>

<h2 id="traceback-对象"><a href="#traceback-对象" class="headerlink" title="traceback 对象"></a>traceback 对象</h2><p>traceback对象包含了出现异常的位置信息，主要是抛出异常的文件及行号(tb_lineno)，如果异常出现在函数中，会递归地记录函数内部抛出异常的位置。多个traceback对象通过tb_next属性以链表的结构储存。</p>
<p>在打印异常信息时，会递归地打印出所有的信息，通过这些信息，我们知道了出现异常的文件和行号，方便修复异常。当函数调用的层数较多时，打印的信息太多反而不容易排查异常，这时候我们可以通过自己捕获和处理异常，限制回溯的层数。</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> traceback <span class="keyword">as</span> tb</span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">raise</span> TypeError(<span class="string">&quot;msg&quot;</span>)</span><br><span class="line"><span class="keyword">except</span> TypeError <span class="keyword">as</span> e:</span><br><span class="line">    tb.print_exc()          <span class="comment"># 递归打印异常详情</span></span><br><span class="line">    tb.print_exc(limit=<span class="number">1</span>)   <span class="comment"># 限制回溯层数，最多只打印1条异常信息</span></span><br></pre></td></tr></table></figure>

<h2 id="print-tb-vs-print-exc"><a href="#print-tb-vs-print-exc" class="headerlink" title="print_tb vs. print_exc"></a>print_tb vs. print_exc</h2><p>print_tb是一个与print_exc相似的函数，使用print_tb函数时需要传入具体的trackback对象，但是，print_tb(tb_obj)与print_exc()功能并不完全一样，两者是包含关系，print_exc打印的信息更多.</p>
<p>print_tb只打印对应异常的回溯信息，print_exc还会打印<code>Exception.__context__</code>中所有的回溯信息。</p>
<p><code>Exception.__context__</code>属性是什么呢? 当捕获了异常(原异常)之后，在except代码块里，如果又产生了新异常，这时新异常的<code>__context__</code>属性就会被置为原异常。这么做是有原因的，因为原异常产生并被捕获了才会执行except代码块里的语句，所以新异常的产生也是由原异常导致的，如果原异常没有产生，根本不需要执行except代码块。因此需要将原异常记录下来以备以后溯源。下面是一个测试：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="keyword">raise</span> TypeError(<span class="string">&quot;type error&quot;</span>)</span><br><span class="line">    <span class="keyword">except</span>:</span><br><span class="line">        <span class="keyword">raise</span> ValueError(<span class="string">&quot;value error&quot;</span>)</span><br><span class="line"><span class="keyword">except</span> ValueError <span class="keyword">as</span> e:</span><br><span class="line">    tb.print_tb(e.__traceback__)</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&quot;--dividing line--&quot;</span>)</span><br><span class="line">    tb.print_exc()</span><br></pre></td></tr></table></figure>

<h2 id="raise-关键字"><a href="#raise-关键字" class="headerlink" title="raise 关键字"></a>raise 关键字</h2><p>raise关键字可以主动抛出异常，有时候我们还会见到类似与raise…from None的语句。将上面代码改成这种形式之后,发现print_exc函数不再打印<code>__context__</code>属性中的异常信息了。</p>
<p>事实上，异常对象中有四个特殊的属性：</p>
<ul>
<li><code>__cause__</code>：由raise…from e语句将<code>__cause__</code>置为e</li>
<li><code>__context__</code>：在except代码块中，当处理异常时发生了新的异常，自动置为原异常</li>
<li><code>__supress_context__</code>：布尔值，False表示打印与否取决于<code>__contex__</code>，True表示抑制<code>__context__</code>，打印与否取决于<code>__cause__</code>。默认为False，raise …from …语句可将其置为True</li>
<li><code>__traceback__</code>：异常对应的traceback对象，包含发生异常的位置信息</li>
</ul>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="keyword">raise</span> TypeError(<span class="string">&quot;type error&quot;</span>)</span><br><span class="line">    <span class="keyword">except</span> TypeError <span class="keyword">as</span> e:</span><br><span class="line">        <span class="keyword">raise</span> ValueError(<span class="string">&quot;value error&quot;</span>)</span><br><span class="line"><span class="keyword">except</span> ValueError <span class="keyword">as</span> e:</span><br><span class="line">    <span class="keyword">assert</span> e.__context__.__class__ == TypeError</span><br><span class="line">    <span class="keyword">assert</span> e.__cause__ == <span class="literal">None</span></span><br><span class="line">    <span class="keyword">assert</span> e.__suppress_context__ == <span class="literal">False</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="keyword">raise</span> TypeError(<span class="string">&quot;type error&quot;</span>)</span><br><span class="line">    <span class="keyword">except</span> TypeError <span class="keyword">as</span> e:</span><br><span class="line">        <span class="keyword">raise</span> ValueError(<span class="string">&quot;value error&quot;</span>) <span class="keyword">from</span> <span class="literal">None</span></span><br><span class="line"><span class="keyword">except</span> ValueError <span class="keyword">as</span> e:</span><br><span class="line">    <span class="keyword">assert</span> e.__context__.__class__ == TypeError</span><br><span class="line">    <span class="keyword">assert</span> e.__cause__ == <span class="literal">None</span></span><br><span class="line">    <span class="keyword">assert</span> e.__suppress_context__ == <span class="literal">True</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="keyword">raise</span> TypeError(<span class="string">&quot;type error&quot;</span>)</span><br><span class="line">    <span class="keyword">except</span> TypeError <span class="keyword">as</span> e:</span><br><span class="line">        <span class="keyword">raise</span> ValueError(<span class="string">&quot;value error&quot;</span>) <span class="keyword">from</span> e</span><br><span class="line"><span class="keyword">except</span> ValueError <span class="keyword">as</span> e:</span><br><span class="line">    <span class="keyword">assert</span> e.__context__.__class__ == TypeError</span><br><span class="line">    <span class="keyword">assert</span> e.__cause__.__class__ == TypeError</span><br><span class="line">    <span class="keyword">assert</span> e.__suppress_context__ == <span class="literal">True</span></span><br></pre></td></tr></table></figure>

<p>单独的raise语句在except代码块中使用，表示直接抛出当前异常，如果在没有异常的上下文中，则抛出RuntimeError。</p>
<h2 id="内置Exception"><a href="#内置Exception" class="headerlink" title="内置Exception"></a>内置Exception</h2><p>Python中的内置异常可以参考官方文档中的<a target="_blank" rel="noopener" href="https://docs.python.org/zh-cn/3/library/exceptions.html?highlight=exception#exception-hierarchy">异常层次结构</a></p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br></pre></td><td class="code"><pre><span class="line">BaseException</span><br><span class="line"> +-- SystemExit</span><br><span class="line"> +-- KeyboardInterrupt</span><br><span class="line"> +-- GeneratorExit</span><br><span class="line"> +-- Exception</span><br><span class="line">      +-- StopIteration</span><br><span class="line">      +-- StopAsyncIteration</span><br><span class="line">      +-- ArithmeticError</span><br><span class="line">      |    +-- FloatingPointError</span><br><span class="line">      |    +-- OverflowError</span><br><span class="line">      |    +-- ZeroDivisionError</span><br><span class="line">      +-- AssertionError</span><br><span class="line">      +-- AttributeError</span><br><span class="line">      +-- BufferError</span><br><span class="line">      +-- EOFError</span><br><span class="line">      +-- ImportError</span><br><span class="line">      |    +-- ModuleNotFoundError</span><br><span class="line">      +-- LookupError</span><br><span class="line">      |    +-- IndexError</span><br><span class="line">      |    +-- KeyError</span><br><span class="line">      +-- MemoryError</span><br><span class="line">      +-- NameError</span><br><span class="line">      |    +-- UnboundLocalError</span><br><span class="line">      +-- OSError</span><br><span class="line">      |    +-- BlockingIOError</span><br><span class="line">      |    +-- ChildProcessError</span><br><span class="line">      |    +-- ConnectionError</span><br><span class="line">      |    |    +-- BrokenPipeError</span><br><span class="line">      |    |    +-- ConnectionAbortedError</span><br><span class="line">      |    |    +-- ConnectionRefusedError</span><br><span class="line">      |    |    +-- ConnectionResetError</span><br><span class="line">      |    +-- FileExistsError</span><br><span class="line">      |    +-- FileNotFoundError</span><br><span class="line">      |    +-- InterruptedError</span><br><span class="line">      |    +-- IsADirectoryError</span><br><span class="line">      |    +-- NotADirectoryError</span><br><span class="line">      |    +-- PermissionError</span><br><span class="line">      |    +-- ProcessLookupError</span><br><span class="line">      |    +-- TimeoutError</span><br><span class="line">      +-- ReferenceError</span><br><span class="line">      +-- RuntimeError</span><br><span class="line">      |    +-- NotImplementedError</span><br><span class="line">      |    +-- RecursionError</span><br><span class="line">      +-- SyntaxError</span><br><span class="line">      |    +-- IndentationError</span><br><span class="line">      |         +-- TabError</span><br><span class="line">      +-- SystemError</span><br><span class="line">      +-- TypeError</span><br><span class="line">      +-- ValueError</span><br><span class="line">      |    +-- UnicodeError</span><br><span class="line">      |         +-- UnicodeDecodeError</span><br><span class="line">      |         +-- UnicodeEncodeError</span><br><span class="line">      |         +-- UnicodeTranslateError</span><br><span class="line">      +-- Warning</span><br><span class="line">           +-- DeprecationWarning</span><br><span class="line">           +-- PendingDeprecationWarning</span><br><span class="line">           +-- RuntimeWarning</span><br><span class="line">           +-- SyntaxWarning</span><br><span class="line">           +-- UserWarning</span><br><span class="line">           +-- FutureWarning</span><br><span class="line">           +-- ImportWarning</span><br><span class="line">           +-- UnicodeWarning</span><br><span class="line">           +-- BytesWarning</span><br><span class="line">           +-- ResourceWarning</span><br></pre></td></tr></table></figure>

<h2 id="总结"><a href="#总结" class="headerlink" title="总结"></a>总结</h2><p>一般不需要直接使用traceback模块，如果要记录程序运行中的错误信息，应当使用日志工具。但是在contextmanager对象中，<code>__exit__</code>函数使用了exc_type，exc_value，exc_traceback作为三个参数，需要在退出上下文时处理可能发生的异常，因此理解异常对象也有助于理解上下文管理器对象。</p>

      
    </div>
    <footer class="article-footer">
      <a data-url="http://example.com/2021/06/15/traceback/" data-id="ckqlumhi60001b4pwd1bvhcdx" data-title="TraceBack模块和Exception类" class="article-share-link">Partager</a>
      
      
      
  <ul class="article-tag-list" itemprop="keywords"><li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/python/" rel="tag">python</a></li></ul>

    </footer>
  </div>
  
    
<nav id="article-nav">
  
    <a href="/2021/06/16/contexmanager/" id="article-nav-newer" class="article-nav-link-wrap">
      <strong class="article-nav-caption">Récent</strong>
      <div class="article-nav-title">
        
          Contextlib模块和生成器
        
      </div>
    </a>
  
  
</nav>

  
</article>


</section>
        
          <aside id="sidebar">
  
    

  
    
  <div class="widget-wrap">
    <h3 class="widget-title">Mot-clés</h3>
    <div class="widget">
      <ul class="tag-list" itemprop="keywords"><li class="tag-list-item"><a class="tag-list-link" href="/tags/git/" rel="tag">git</a></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/nginx/" rel="tag">nginx</a></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/python/" rel="tag">python</a></li></ul>
    </div>
  </div>


  
    
  <div class="widget-wrap">
    <h3 class="widget-title">Nuage de mot-clés</h3>
    <div class="widget tagcloud">
      <a href="/tags/git/" style="font-size: 20px;">git</a> <a href="/tags/nginx/" style="font-size: 10px;">nginx</a> <a href="/tags/python/" style="font-size: 20px;">python</a>
    </div>
  </div>

  
    
  <div class="widget-wrap">
    <h3 class="widget-title">Archives</h3>
    <div class="widget">
      <ul class="archive-list"><li class="archive-list-item"><a class="archive-list-link" href="/archives/2021/07/">七月 2021</a></li><li class="archive-list-item"><a class="archive-list-link" href="/archives/2021/06/">六月 2021</a></li></ul>
    </div>
  </div>


  
    
  <div class="widget-wrap">
    <h3 class="widget-title">Articles récents</h3>
    <div class="widget">
      <ul>
        
          <li>
            <a href="/2021/07/04/git-basic/">Git基本操作</a>
          </li>
        
          <li>
            <a href="/2021/07/02/git-core/">Git内部原理</a>
          </li>
        
          <li>
            <a href="/2021/06/18/nginx/">Nginx配置</a>
          </li>
        
          <li>
            <a href="/2021/06/16/contexmanager/">Contextlib模块和生成器</a>
          </li>
        
          <li>
            <a href="/2021/06/15/traceback/">TraceBack模块和Exception类</a>
          </li>
        
      </ul>
    </div>
  </div>

  
</aside>
        
      </div>
      <footer id="footer">
  
  <div class="outer">
    <div id="footer-info" class="inner">
      
      &copy; 2021 DHao<br>
      Propulsé par <a href="https://hexo.io/" target="_blank">Hexo</a>
    </div>
  </div>
</footer>

    </div>
    <nav id="mobile-nav">
  
    <a href="/" class="mobile-nav-link">Home</a>
  
    <a href="/archives" class="mobile-nav-link">Archives</a>
  
</nav>
    


<script src="/js/jquery-3.4.1.min.js"></script>



  
<script src="/fancybox/jquery.fancybox.min.js"></script>




<script src="/js/script.js"></script>





  </div>
</body>
</html>